services:
  db: 
    image: postgis/postgis:18-3.6
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - .env
      - .env.public
    environment: 
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: