services:
  db: 
    image: postgis/postgis:18-3.6
    ports:
      - "${DATABASE_PORT}:5432"
    env_file:
      - ./apps/server/.env
    environment: 
      POSTGRES_USER: "${DATABASE_USER}"
      POSTGRES_PASSWORD: "${DATABASE_PASSWORD}"
      POSTGRES_DB: "${DATABASE_NAME}"
    volumes:
      - pgdata-temp:/var/lib/postgresql
      - ./packages/db/drizzle/0000_init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata-temp: