packages:
  - apps/*
  - packages/*

catalog:
  '@better-auth/expo': ^1.6.9
  '@better-auth/drizzle-adapter': ^1.6.22
  better-auth: ^1.6.9
  date-fns: 4.4.0
  dotenv: ^17.2.2
  # drizzle-orm: ^0.45.2
  # drizzle-kit: ^0.31.10
  drizzle-orm: rc
  drizzle-kit: rc
  typescript: ^6
  zod: ^4.1.13
  zod-validation-error: ^5.0.0
  axios: ^1.17.0
  
onlyBuiltDependencies:
  - '@swc/core'
